source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', tag: 'v8.0.3', github: 'rails/rails'
# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem 'propshaft', tag: 'v1.3.1', github: 'rails/propshaft'
# Use postgresql as the database for Active Record
gem 'pg', tag: 'v1.6.2', github: 'ged/ruby-pg'
# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', tag: 'v7.1.0', github: 'puma/puma'
# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem 'importmap-rails', tag: 'v2.2.2', github: 'rails/importmap-rails'
# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem 'turbo-rails', tag: 'v2.0.17', github: 'hotwired/turbo-rails'
# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem 'stimulus-rails', tag: 'v1.3.4', github: 'hotwired/stimulus-rails'
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem 'jbuilder', tag: 'v2.14.1', github: 'rails/jbuilder'

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem 'bcrypt', tag: 'v3.1.20', github: 'bcrypt-ruby/bcrypt-ruby'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[windows jruby], tag: 'v1.2025.2', github: 'tzinfo/tzinfo-data'

# Use the database-backed adapters for Rails.cache and Active Job
gem 'solid_cache', tag: 'v1.0.8',  github: 'rails/solid_cache'
gem 'solid_queue', tag: 'v1.2.1',  github: 'rails/solid_queue'
gem 'solid_cable', tag: 'v3.0.12', github: 'rails/solid_cable'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', tag: 'v1.18.6', github: 'rails/bootsnap', require: false
# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem 'kamal', tag: 'v2.7.0', github: 'basecamp/kamal', require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem 'thruster', tag: 'v0.1.15', github: 'basecamp/thruster', require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem 'image_processing', tag: 'v1.14.0', github: 'janko/image_processing', require: false

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', tag: 'v1.11.0', github: 'ruby/debug', platforms: %i[mri windows], require: 'debug/prelude'

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem 'brakeman', tag: 'v7.1.0', github: 'presidentbeef/brakeman', require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem 'rubocop-rails-omakase', tag: 'v1.1.0', github: 'rails/rubocop-rails-omakase', require: false
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem 'web-console', tag: 'v4.2.1', github: 'rails/web-console'
end
